import './globals.css';

import { Montserrat } from 'next/font/google';
import MainContextProvider from '@/store/MainContext';
// import { SpeedInsights } from '@vercel/speed-insights/next';

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
});

export const metadata = {
  title: 'AirQualityApp',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={montserrat.variable}>
      <body>
          <MainContextProvider>{children}</MainContextProvider>
        {/* <SpeedInsights /> */}
      </body>
    </html>
  );
}
